# Generated by Django 4.2.13 on 2026-04-30 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched_bank', 'Unmatched - Bank only'), ('unmatched_ledger', 'Unmatched - Ledger only')], max_length=20)),
                ('match_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='ingestion.banktransaction')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='ingestion.ledgerentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
