# Generated by Django 4.2.13 on 2026-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresult',
            name='amount_discrepancy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
