# Generated by Django 4.2.13 on 2026-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_reconciliationresult_amount_discrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationresult',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('unmatched_bank', 'Unmatched - Bank only'), ('unmatched_ledger', 'Unmatched - Ledger only')], max_length=30),
        ),
    ]
